server {
    listen 80;

    # 1. Tell Nginx to use Docker/Render's internal DNS
    resolver 127.0.0.11 valid=30s;

    location /api/ {
    
        set $backend_service "http://my-app-backend:3000";

        proxy_pass $backend_service;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}