# --- STEP 1: Dependencies ---
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# --- STEP 2: Development (Stop here for dev) ---
FROM base AS development
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]

# --- STEP 3: Build Stage ---
FROM base AS builder
COPY . .
RUN npm run build

# --- STEP 4: Production (The final tiny image) ---
FROM node:20-alpine AS production
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]