import {
  StateSchema,
  MessagesValue,
  type GraphNode,
  type CompiledStateGraph,
  START,
  END,
  StateGraph,
} from "@langchain/langgraph";
import { z } from "zod";
import { modelFactory, judgeModel } from "./modes.service.js";
import { HumanMessage, createAgent, providerStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  m1_config: z.object({ provider: z.string(), name: z.string() }),
  m2_config: z.object({ provider: z.string(), name: z.string() }),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const model1 = modelFactory(state.m1_config.provider, state.m1_config.name);
  const model2 = modelFactory(state.m2_config.provider, state.m2_config.name);

  const [model1Response, model2Response] = await Promise.all([
    model1.invoke(state.problem),
    model2.invoke(state.problem),
  ]);

  return {
    solution_1: model1Response.text,
    solution_2: model2Response.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: judgeModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(
        ` Problem: ${problem}
        Solution 1: ${solution_1}
        Solution 2: ${solution_2}
        Please evaluate the solutions and provide scores and reasoning.`,
      ),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function (problem: string, m1: any, m2: any) {
  const result = await graph.invoke({
    problem: problem,
    m1_config: m1,
    m2_config: m2,
  });

  return result;
}
